#!/bin/bash
#


# Source function library.
if [ -f /etc/rc.d/functions ];
then
    . /etc/init.d/functions
fi

# ${app_name}
 Service script for Linux

start()
{
	echo $"Starting PostgreSQL:"
	su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/converis/postgres/lib:$LD_LIBRARY_PATH /opt/converis/postgres/bin/pg_ctl -w start -D \"/opt/converis/postgres/data\" -l \"/opt/converis/postgres/data/pg_log/startup.log\""
	
	if [ $? -eq 0 ];
	then
		echo "PostgreSQL started successfully"
                exit 0
	else
		echo "PostgreSQL did not start in a timely fashion, please see /opt/converis/postgres/data/pg_log/startup.log for details"
                exit 1
	fi
}

stop()
{
	echo $"Stopping PostgreSQL:"
	su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/converis/postgres/lib:$LD_LIBRARY_PATH /opt/converis/postgres/bin/pg_ctl stop -m fast -w -D \"/opt/converis/postgres/data\""
}

restart()
{
	echo $"Restarting PostgreSQL:"
	su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/converis/postgres/lib:$LD_LIBRARY_PATH /opt/converis/postgres/bin/pg_ctl -w restart -D \"/opt/converis/postgres/data\" -l \"/opt/converis/postgres/data/pg_log/startup.log\" -m fast"
	
	if [ $? -eq 0 ];
	then
		echo "PostgreSQL restarted successfully"
                exit 0
	else
		echo "PostgreSQL did not start in a timely fashion, please see /opt/converis/postgres/data/pg_log/startup.log for details"
                exit 1
	fi
}

reload()
{
	echo $"Reloading PostgreSQL:"
	su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/converis/postgres/lib:$LD_LIBRARY_PATH /opt/converis/postgres/bin/pg_ctl reload -D \"/opt/converis/postgres/data\""
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload)
	reload
	;;
  condrestart)
        if [ -f "/opt/converis/postgres/data/postmaster.pid" ]; then
            restart
        fi
        ;;
  status)
        su -s /bin/sh - postgres -c "LD_LIBRARY_PATH=/opt/converis/postgres/lib:$LD_LIBRARY_PATH /opt/converis/postgres/bin/pg_ctl status -D \"/opt/converis/postgres/data\""
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|condrestart|status}"
        exit 1
esac

